name: CI/CD MLflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CSV_URL: "MLProject/top_1000_books_preprocessing.csv"
  TARGET_VAR: "bestseller_status"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 2. Setup Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Check Env
        run: echo $CSV_URL

      # 3. Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas scikit-learn matplotlib seaborn numpy

      # 4. Train Model
      # PENTING: Pastikan path file script training Anda benar!
      # Saya asumsikan ada di folder 'modelling' dengan nama file di bawah ini.
      - name: Train Model & Log to MLflow
        run: |
          python modelling/train_model.py

      - name: run MLProject
        run: |
          mlflow run MLProject --env-manager=local
      
      - name: Get latest MLflow run_id
        run: |
          # Cari Run ID (folder hash acak) di dalam folder eksperimen apapun di mlruns
          # ls -td mengurutkan berdasarkan waktu (terbaru di atas)
          RUN_ID=$(ls -td mlruns/*/* | head -n 1 | awk -F'/' '{print $3}')
          
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Detected Latest RUN_ID: $RUN_ID"

      # 6. Build Docker Image (Membuat Container dari Model)
      - name: Build Docker model
        run: |
          # --enable-mlserver opsional, dihapus jika error
          mlflow models build-docker \
            --model-uri "runs:/$RUN_ID/model" \
            --name "book-popularity-model" 

      # 7. Login ke Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 8. Tag & Push Image ke Docker Hub
      - name: Tag Docker image
        run: |
          docker tag cc ${{ secrets.DOCKERHUB_USERNAME }}/cc:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cc:latest
          
          docker tag book-popularity-model $IMAGE_TAG
